Repository sonic-net/sonic-host-services, pull requests merged in 2024-08, with the labels that each got.

#146 [action] [PR:126] Added a try block to prevent JSON decoder errors (#126)
  scripts/process-reboot-cause
Labels: automerge

#148 [action] [PR:126] Added a try block to prevent JSON decoder errors (#126)
  scripts/process-reboot-cause
Labels: automerge

#147 [action] [PR:126] Added a try block to prevent JSON decoder errors (#126)
  scripts/process-reboot-cause
Labels: automerge

#152 [action] [PR:136] Modified scripts: replaced deprecated 'logger' with 'syslogger' (#136)
  scripts/determine-reboot-cause
  scripts/process-reboot-cause
Labels: automerge

#151 [action] [PR:145] Fix modify_single_file generate empty file issue (#145)
  scripts/hostcfgd
Labels: automerge

#93 Password Hardening: Add support to disable expiration date
  scripts/hostcfgd
  tests/hostcfgd/sample_output/PASSWORD_HARDENING_enable_digits_class/login.defs
Labels: Request for 202305 Branch, Request for 202311 Branch, Request for 202405 Branch

#153 [action] [PR:145] Fix modify_single_file generate empty file issue (#145)
  scripts/hostcfgd
Labels: automerge

#154 [action] [PR:103] Update ProcessStats query by using API instead of parsing ps command. (#103)
  azure-pipelines.yml
  scripts/procdockerstatsd
  tests/procdockerstatsd_test.py
Labels: automerge

#156 [action] [PR:117] Fix UT test data due to timestamp break. (#117)
  tests/procdockerstatsd_test.py
Labels: automerge

#155 [action] [PR:110] Change dependency option to fix buildimage issue. (#110)
  azure-pipelines.yml
  scripts/procdockerstatsd
  setup.py
Labels: automerge

#150 [BFD]Fix BFD blackout issue
  scripts/caclmgrd
  tests/caclmgrd/caclmgrd_bfd_test.py
  tests/caclmgrd/test_bfd_vectors.py
Labels: Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch, Request for 202405 Branch
