Repository sonic-net/sonic-host-services, pull requests merged in 2024-05, with the labels that each got.

#107 Fix issue: delayed service will not be restarted if swss crashes
  scripts/featured
  tests/featured/featured_test.py
Labels: bug, Request for 202311 Branch

#124 [action] [PR:107] Fix issue: delayed service will not be restarted if swss crashes (#107)
  scripts/featured
  tests/featured/featured_test.py
Labels: automerge

#126 Added code to process-reboot-check that mitigates JSON decoder errors
  scripts/process-reboot-cause
Labels: Request for 202305 Branch, Request for 202311 Branch

#120 Added support to render Feature Table has_global_scope field.
  scripts/featured
  tests/featured/featured_test.py
  tests/featured/test_vectors.py
Labels: chassis

#129 [action] [PR:106] Fix hostcfgd crash when delete entire config table. (#106)
  scripts/hostcfgd
  tests/common/mock_configdb.py
  tests/hostcfgd/hostcfgd_tacacs_test.py
Labels: automerge
