Repository sonic-net/sonic-host-services, pull requests merged in 2024-07, with the labels that each got.

#135 Added support to render template format of `delayed` flag on Feature Table.
  scripts/featured
  tests/featured/featured_test.py
  tests/featured/test_vectors.py
Labels: Request for 202405 Branch

#138 [action] [PR:132] Fixed determine/process reboot-cause service dependency (#17406) (#132)
  data/debian/sonic-host-services-data.determine-reboot-cause.service
  data/debian/sonic-host-services-data.process-reboot-cause.service
  data/debian/sonic-host-services-data.process-reboot-cause.timer
Labels: automerge

#137 [action] [PR:135] Added support to render template format of `delayed` flag on Feature Table. (#135)
  scripts/featured
  tests/featured/featured_test.py
  tests/featured/test_vectors.py
Labels: automerge

#136 Modified scripts: replaced deprecated 'logger' with 'syslogger'
  scripts/determine-reboot-cause
  scripts/process-reboot-cause
Labels: Request for 202305 Branch, Request for 202405 Branch

#140 [action] [PR:133] Ignore sonic_platform package fileNotFoundError on non-chassis vs platforms (#133)
  scripts/determine-reboot-cause
Labels: automerge

#141 [action] [PR:139] Fix security vulnerability in caclmgrd (#139)
  scripts/caclmgrd
Labels: automerge
